baseURL = "/"
languageCode = "en-us"
title = "kmb"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Katie McCall Brown"
    description = "Katie McCall Brown<br />Aspiring Data Scientist"
    githubUsername = "#"
    accent = "#F84261"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/resume"
    name = "Resume"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:katiemccallbrown@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ktmbrown/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/ktmccallbrown/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/katie-brown-393b97171/"
    name = "linkedin"
    weight = 4

